<Project>
<ItemGroup>
<PackageReference Include="Pkg0" Version="1.0.0" />
<PackageReference Include="Pkg1" Version="1.0.1" />
<PackageReference Include="Pkg2" Version="1.0.2" />
<PackageReference Include="Pkg3" Version="1.0.3" />
<PackageReference Include="Pkg4" Version="1.0.4" />
<PackageReference Include="Pkg5" Version="1.0.5" />
<PackageReference Include="Pkg6" Version="1.0.6" />
<PackageReference Include="Pkg7" Version="1.0.7" />
<PackageReference Include="Pkg8" Version="1.0.8" />
<PackageReference Include="Pkg9" Version="1.0.9" />
<PackageReference Include="Pkg10" Version="1.0.10" />
<PackageReference Include="Pkg11" Version="1.0.11" />
<PackageReference Include="Pkg12" Version="1.0.12" />
<PackageReference Include="Pkg13" Version="1.0.13" />
<PackageReference Include="Pkg14" Version="1.0.14" />
<PackageReference Include="Pkg15" Version="1.0.15" />
<PackageReference Include="Pkg16" Version="1.0.16" />
<PackageReference Include="Pkg17" Version="1.0.17" />
<PackageReference Include="Pkg18" Version="1.0.18" />
<PackageReference Include="Pkg19" Version="1.0.19" />
<PackageReference Include="Pkg20" Version="1.0.20" />
<PackageReference Include="Pkg21" Version="1.0.21" />
<PackageReference Include="Pkg22" Version="1.0.22" />
<PackageReference Include="Pkg23" Version="1.0.23" />
<PackageReference Include="Pkg24" Version="1.0.24" />
<PackageReference Include="Pkg25" Version="1.0.25" />
<PackageReference Include="Pkg26" Version="1.0.26" />
<PackageReference Include="Pkg27" Version="1.0.27" />
<PackageReference Include="Pkg28" Version="1.0.28" />
<PackageReference Include="Pkg29" Version="1.0.29" />
<PackageReference Include="Pkg30" Version="1.0.30" />
<PackageReference Include="Pkg31" Version="1.0.31" />
<PackageReference Include="Pkg32" Version="1.0.32" />
<PackageReference Include="Pkg33" Version="1.0.33" />
<PackageReference Include="Pkg34" Version="1.0.34" />
<PackageReference Include="Pkg35" Version="1.0.35" />
<PackageReference Include="Pkg36" Version="1.0.36" />
<PackageReference Include="Pkg37" Version="1.0.37" />
<PackageReference Include="Pkg38" Version="1.0.38" />
<PackageReference Include="Pkg39" Version="1.0.39" />
<PackageReference Include="Pkg40" Version="1.0.40" />
<PackageReference Include="Pkg41" Version="1.0.41" />
<PackageReference Include="Pkg42" Version="1.0.42" />
<PackageReference Include="Pkg43" Version="1.0.43" />
<PackageReference Include="Pkg44" Version="1.0.44" />
<PackageReference Include="Pkg45" Version="1.0.45" />
<PackageReference Include="Pkg46" Version="1.0.46" />
<PackageReference Include="Pkg47" Version="1.0.47" />
<PackageReference Include="Pkg48" Version="1.0.48" />
<PackageReference Include="Pkg49" Version="1.0.49" />
<PackageReference Include="Pkg50" Version="1.0.50" />
<PackageReference Include="Pkg51" Version="1.0.51" />
<PackageReference Include="Pkg52" Version="1.0.52" />
<PackageReference Include="Pkg53" Version="1.0.53" />
<PackageReference Include="Pkg54" Version="1.0.54" />
<PackageReference Include="Pkg55" Version="1.0.55" />
<PackageReference Include="Pkg56" Version="1.0.56" />
<PackageReference Include="Pkg57" Version="1.0.57" />
<PackageReference Include="Pkg58" Version="1.0.58" />
<PackageReference Include="Pkg59" Version="1.0.59" />
<PackageReference Include="Pkg60" Version="1.0.60" />
<PackageReference Include="Pkg61" Version="1.0.61" />
<PackageReference Include="Pkg62" Version="1.0.62" />
<PackageReference Include="Pkg63" Version="1.0.63" />
<PackageReference Include="Pkg64" Version="1.0.64" />
<PackageReference Include="Pkg65" Version="1.0.65" />
<PackageReference Include="Pkg66" Version="1.0.66" />
<PackageReference Include="Pkg67" Version="1.0.67" />
<PackageReference Include="Pkg68" Version="1.0.68" />
<PackageReference Include="Pkg69" Version="1.0.69" />
<PackageReference Include="Pkg70" Version="1.0.70" />
<PackageReference Include="Pkg71" Version="1.0.71" />
<PackageReference Include="Pkg72" Version="1.0.72" />
<PackageReference Include="Pkg73" Version="1.0.73" />
<PackageReference Include="Pkg74" Version="1.0.74" />
<PackageReference Include="Pkg75" Version="1.0.75" />
<PackageReference Include="Pkg76" Version="1.0.76" />
<PackageReference Include="Pkg77" Version="1.0.77" />
<PackageReference Include="Pkg78" Version="1.0.78" />
<PackageReference Include="Pkg79" Version="1.0.79" />
<PackageReference Include="Pkg80" Version="1.0.80" />
<PackageReference Include="Pkg81" Version="1.0.81" />
<PackageReference Include="Pkg82" Version="1.0.82" />
<PackageReference Include="Pkg83" Version="1.0.83" />
<PackageReference Include="Pkg84" Version="1.0.84" />
<PackageReference Include="Pkg85" Version="1.0.85" />
<PackageReference Include="Pkg86" Version="1.0.86" />
<PackageReference Include="Pkg87" Version="1.0.87" />
<PackageReference Include="Pkg88" Version="1.0.88" />
<PackageReference Include="Pkg89" Version="1.0.89" />
<PackageReference Include="Pkg90" Version="1.0.90" />
<PackageReference Include="Pkg91" Version="1.0.91" />
<PackageReference Include="Pkg92" Version="1.0.92" />
<PackageReference Include="Pkg93" Version="1.0.93" />
<PackageReference Include="Pkg94" Version="1.0.94" />
<PackageReference Include="Pkg95" Version="1.0.95" />
<PackageReference Include="Pkg96" Version="1.0.96" />
<PackageReference Include="Pkg97" Version="1.0.97" />
<PackageReference Include="Pkg98" Version="1.0.98" />
<PackageReference Include="Pkg99" Version="1.0.99" />
<PackageReference Include="Pkg100" Version="1.0.100" />
<PackageReference Include="Pkg101" Version="1.0.101" />
<PackageReference Include="Pkg102" Version="1.0.102" />
<PackageReference Include="Pkg103" Version="1.0.103" />
<PackageReference Include="Pkg104" Version="1.0.104" />
<PackageReference Include="Pkg105" Version="1.0.105" />
<PackageReference Include="Pkg106" Version="1.0.106" />
<PackageReference Include="Pkg107" Version="1.0.107" />
<PackageReference Include="Pkg108" Version="1.0.108" />
<PackageReference Include="Pkg109" Version="1.0.109" />
<PackageReference Include="Pkg110" Version="1.0.110" />
<PackageReference Include="Pkg111" Version="1.0.111" />
<PackageReference Include="Pkg112" Version="1.0.112" />
<PackageReference Include="Pkg113" Version="1.0.113" />
<PackageReference Include="Pkg114" Version="1.0.114" />
<PackageReference Include="Pkg115" Version="1.0.115" />
<PackageReference Include="Pkg116" Version="1.0.116" />
<PackageReference Include="Pkg117" Version="1.0.117" />
<PackageReference Include="Pkg118" Version="1.0.118" />
<PackageReference Include="Pkg119" Version="1.0.119" />
<PackageReference Include="Pkg120" Version="1.0.120" />
<PackageReference Include="Pkg121" Version="1.0.121" />
<PackageReference Include="Pkg122" Version="1.0.122" />
<PackageReference Include="Pkg123" Version="1.0.123" />
<PackageReference Include="Pkg124" Version="1.0.124" />
<PackageReference Include="Pkg125" Version="1.0.125" />
<PackageReference Include="Pkg126" Version="1.0.126" />
<PackageReference Include="Pkg127" Version="1.0.127" />
<PackageReference Include="Pkg128" Version="1.0.128" />
<PackageReference Include="Pkg129" Version="1.0.129" />
<PackageReference Include="Pkg130" Version="1.0.130" />
<PackageReference Include="Pkg131" Version="1.0.131" />
<PackageReference Include="Pkg132" Version="1.0.132" />
<PackageReference Include="Pkg133" Version="1.0.133" />
<PackageReference Include="Pkg134" Version="1.0.134" />
<PackageReference Include="Pkg135" Version="1.0.135" />
<PackageReference Include="Pkg136" Version="1.0.136" />
<PackageReference Include="Pkg137" Version="1.0.137" />
<PackageReference Include="Pkg138" Version="1.0.138" />
<PackageReference Include="Pkg139" Version="1.0.139" />
<PackageReference Include="Pkg140" Version="1.0.140" />
<PackageReference Include="Pkg141" Version="1.0.141" />
<PackageReference Include="Pkg142" Version="1.0.142" />
<PackageReference Include="Pkg143" Version="1.0.143" />
<PackageReference Include="Pkg144" Version="1.0.144" />
<PackageReference Include="Pkg145" Version="1.0.145" />
<PackageReference Include="Pkg146" Version="1.0.146" />
<PackageReference Include="Pkg147" Version="1.0.147" />
<PackageReference Include="Pkg148" Version="1.0.148" />
<PackageReference Include="Pkg149" Version="1.0.149" />
<PackageReference Include="Pkg150" Version="1.0.150" />
<PackageReference Include="Pkg151" Version="1.0.151" />
<PackageReference Include="Pkg152" Version="1.0.152" />
<PackageReference Include="Pkg153" Version="1.0.153" />
<PackageReference Include="Pkg154" Version="1.0.154" />
<PackageReference Include="Pkg155" Version="1.0.155" />
<PackageReference Include="Pkg156" Version="1.0.156" />
<PackageReference Include="Pkg157" Version="1.0.157" />
<PackageReference Include="Pkg158" Version="1.0.158" />
<PackageReference Include="Pkg159" Version="1.0.159" />
<PackageReference Include="Pkg160" Version="1.0.160" />
<PackageReference Include="Pkg161" Version="1.0.161" />
<PackageReference Include="Pkg162" Version="1.0.162" />
<PackageReference Include="Pkg163" Version="1.0.163" />
<PackageReference Include="Pkg164" Version="1.0.164" />
<PackageReference Include="Pkg165" Version="1.0.165" />
<PackageReference Include="Pkg166" Version="1.0.166" />
<PackageReference Include="Pkg167" Version="1.0.167" />
<PackageReference Include="Pkg168" Version="1.0.168" />
<PackageReference Include="Pkg169" Version="1.0.169" />
<PackageReference Include="Pkg170" Version="1.0.170" />
<PackageReference Include="Pkg171" Version="1.0.171" />
<PackageReference Include="Pkg172" Version="1.0.172" />
<PackageReference Include="Pkg173" Version="1.0.173" />
<PackageReference Include="Pkg174" Version="1.0.174" />
<PackageReference Include="Pkg175" Version="1.0.175" />
<PackageReference Include="Pkg176" Version="1.0.176" />
<PackageReference Include="Pkg177" Version="1.0.177" />
<PackageReference Include="Pkg178" Version="1.0.178" />
<PackageReference Include="Pkg179" Version="1.0.179" />
<PackageReference Include="Pkg180" Version="1.0.180" />
<PackageReference Include="Pkg181" Version="1.0.181" />
<PackageReference Include="Pkg182" Version="1.0.182" />
<PackageReference Include="Pkg183" Version="1.0.183" />
<PackageReference Include="Pkg184" Version="1.0.184" />
<PackageReference Include="Pkg185" Version="1.0.185" />
<PackageReference Include="Pkg186" Version="1.0.186" />
<PackageReference Include="Pkg187" Version="1.0.187" />
<PackageReference Include="Pkg188" Version="1.0.188" />
<PackageReference Include="Pkg189" Version="1.0.189" />
<PackageReference Include="Pkg190" Version="1.0.190" />
<PackageReference Include="Pkg191" Version="1.0.191" />
<PackageReference Include="Pkg192" Version="1.0.192" />
<PackageReference Include="Pkg193" Version="1.0.193" />
<PackageReference Include="Pkg194" Version="1.0.194" />
<PackageReference Include="Pkg195" Version="1.0.195" />
<PackageReference Include="Pkg196" Version="1.0.196" />
<PackageReference Include="Pkg197" Version="1.0.197" />
<PackageReference Include="Pkg198" Version="1.0.198" />
<PackageReference Include="Pkg199" Version="1.0.199" />
<PackageReference Include="Pkg200" Version="1.0.200" />
<PackageReference Include="Pkg201" Version="1.0.201" />
<PackageReference Include="Pkg202" Version="1.0.202" />
<PackageReference Include="Pkg203" Version="1.0.203" />
<PackageReference Include="Pkg204" Version="1.0.204" />
<PackageReference Include="Pkg205" Version="1.0.205" />
<PackageReference Include="Pkg206" Version="1.0.206" />
<PackageReference Include="Pkg207" Version="1.0.207" />
<PackageReference Include="Pkg208" Version="1.0.208" />
<PackageReference Include="Pkg209" Version="1.0.209" />
<PackageReference Include="Pkg210" Version="1.0.210" />
<PackageReference Include="Pkg211" Version="1.0.211" />
<PackageReference Include="Pkg212" Version="1.0.212" />
<PackageReference Include="Pkg213" Version="1.0.213" />
<PackageReference Include="Pkg214" Version="1.0.214" />
<PackageReference Include="Pkg215" Version="1.0.215" />
<PackageReference Include="Pkg216" Version="1.0.216" />
<PackageReference Include="Pkg217" Version="1.0.217" />
<PackageReference Include="Pkg218" Version="1.0.218" />
<PackageReference Include="Pkg219" Version="1.0.219" />
<PackageReference Include="Pkg220" Version="1.0.220" />
<PackageReference Include="Pkg221" Version="1.0.221" />
<PackageReference Include="Pkg222" Version="1.0.222" />
<PackageReference Include="Pkg223" Version="1.0.223" />
<PackageReference Include="Pkg224" Version="1.0.224" />
<PackageReference Include="Pkg225" Version="1.0.225" />
<PackageReference Include="Pkg226" Version="1.0.226" />
<PackageReference Include="Pkg227" Version="1.0.227" />
<PackageReference Include="Pkg228" Version="1.0.228" />
<PackageReference Include="Pkg229" Version="1.0.229" />
<PackageReference Include="Pkg230" Version="1.0.230" />
<PackageReference Include="Pkg231" Version="1.0.231" />
<PackageReference Include="Pkg232" Version="1.0.232" />
<PackageReference Include="Pkg233" Version="1.0.233" />
<PackageReference Include="Pkg234" Version="1.0.234" />
<PackageReference Include="Pkg235" Version="1.0.235" />
<PackageReference Include="Pkg236" Version="1.0.236" />
<PackageReference Include="Pkg237" Version="1.0.237" />
<PackageReference Include="Pkg238" Version="1.0.238" />
<PackageReference Include="Pkg239" Version="1.0.239" />
<PackageReference Include="Pkg240" Version="1.0.240" />
<PackageReference Include="Pkg241" Version="1.0.241" />
<PackageReference Include="Pkg242" Version="1.0.242" />
<PackageReference Include="Pkg243" Version="1.0.243" />
<PackageReference Include="Pkg244" Version="1.0.244" />
<PackageReference Include="Pkg245" Version="1.0.245" />
<PackageReference Include="Pkg246" Version="1.0.246" />
<PackageReference Include="Pkg247" Version="1.0.247" />
<PackageReference Include="Pkg248" Version="1.0.248" />
<PackageReference Include="Pkg249" Version="1.0.249" />
<PackageReference Include="Pkg250" Version="1.0.250" />
<PackageReference Include="Pkg251" Version="1.0.251" />
<PackageReference Include="Pkg252" Version="1.0.252" />
<PackageReference Include="Pkg253" Version="1.0.253" />
<PackageReference Include="Pkg254" Version="1.0.254" />
<PackageReference Include="Pkg255" Version="1.0.255" />
<PackageReference Include="Pkg256" Version="1.0.256" />
<PackageReference Include="Pkg257" Version="1.0.257" />
<PackageReference Include="Pkg258" Version="1.0.258" />
<PackageReference Include="Pkg259" Version="1.0.259" />
<PackageReference Include="Pkg260" Version="1.0.260" />
<PackageReference Include="Pkg261" Version="1.0.261" />
<PackageReference Include="Pkg262" Version="1.0.262" />
<PackageReference Include="Pkg263" Version="1.0.263" />
<PackageReference Include="Pkg264" Version="1.0.264" />
<PackageReference Include="Pkg265" Version="1.0.265" />
<PackageReference Include="Pkg266" Version="1.0.266" />
<PackageReference Include="Pkg267" Version="1.0.267" />
<PackageReference Include="Pkg268" Version="1.0.268" />
<PackageReference Include="Pkg269" Version="1.0.269" />
<PackageReference Include="Pkg270" Version="1.0.270" />
<PackageReference Include="Pkg271" Version="1.0.271" />
<PackageReference Include="Pkg272" Version="1.0.272" />
<PackageReference Include="Pkg273" Version="1.0.273" />
<PackageReference Include="Pkg274" Version="1.0.274" />
<PackageReference Include="Pkg275" Version="1.0.275" />
<PackageReference Include="Pkg276" Version="1.0.276" />
<PackageReference Include="Pkg277" Version="1.0.277" />
<PackageReference Include="Pkg278" Version="1.0.278" />
<PackageReference Include="Pkg279" Version="1.0.279" />
<PackageReference Include="Pkg280" Version="1.0.280" />
<PackageReference Include="Pkg281" Version="1.0.281" />
<PackageReference Include="Pkg282" Version="1.0.282" />
<PackageReference Include="Pkg283" Version="1.0.283" />
<PackageReference Include="Pkg284" Version="1.0.284" />
<PackageReference Include="Pkg285" Version="1.0.285" />
<PackageReference Include="Pkg286" Version="1.0.286" />
<PackageReference Include="Pkg287" Version="1.0.287" />
<PackageReference Include="Pkg288" Version="1.0.288" />
<PackageReference Include="Pkg289" Version="1.0.289" />
<PackageReference Include="Pkg290" Version="1.0.290" />
<PackageReference Include="Pkg291" Version="1.0.291" />
<PackageReference Include="Pkg292" Version="1.0.292" />
<PackageReference Include="Pkg293" Version="1.0.293" />
<PackageReference Include="Pkg294" Version="1.0.294" />
<PackageReference Include="Pkg295" Version="1.0.295" />
<PackageReference Include="Pkg296" Version="1.0.296" />
<PackageReference Include="Pkg297" Version="1.0.297" />
<PackageReference Include="Pkg298" Version="1.0.298" />
<PackageReference Include="Pkg299" Version="1.0.299" />
<PackageReference Include="Pkg300" Version="1.0.300" />
<PackageReference Include="Pkg301" Version="1.0.301" />
<PackageReference Include="Pkg302" Version="1.0.302" />
<PackageReference Include="Pkg303" Version="1.0.303" />
<PackageReference Include="Pkg304" Version="1.0.304" />
<PackageReference Include="Pkg305" Version="1.0.305" />
<PackageReference Include="Pkg306" Version="1.0.306" />
<PackageReference Include="Pkg307" Version="1.0.307" />
<PackageReference Include="Pkg308" Version="1.0.308" />
<PackageReference Include="Pkg309" Version="1.0.309" />
<PackageReference Include="Pkg310" Version="1.0.310" />
<PackageReference Include="Pkg311" Version="1.0.311" />
<PackageReference Include="Pkg312" Version="1.0.312" />
<PackageReference Include="Pkg313" Version="1.0.313" />
<PackageReference Include="Pkg314" Version="1.0.314" />
<PackageReference Include="Pkg315" Version="1.0.315" />
<PackageReference Include="Pkg316" Version="1.0.316" />
<PackageReference Include="Pkg317" Version="1.0.317" />
<PackageReference Include="Pkg318" Version="1.0.318" />
<PackageReference Include="Pkg319" Version="1.0.319" />
<PackageReference Include="Pkg320" Version="1.0.320" />
<PackageReference Include="Pkg321" Version="1.0.321" />
<PackageReference Include="Pkg322" Version="1.0.322" />
<PackageReference Include="Pkg323" Version="1.0.323" />
<PackageReference Include="Pkg324" Version="1.0.324" />
<PackageReference Include="Pkg325" Version="1.0.325" />
<PackageReference Include="Pkg326" Version="1.0.326" />
<PackageReference Include="Pkg327" Version="1.0.327" />
<PackageReference Include="Pkg328" Version="1.0.328" />
<PackageReference Include="Pkg329" Version="1.0.329" />
<PackageReference Include="Pkg330" Version="1.0.330" />
<PackageReference Include="Pkg331" Version="1.0.331" />
<PackageReference Include="Pkg332" Version="1.0.332" />
<PackageReference Include="Pkg333" Version="1.0.333" />
<PackageReference Include="Pkg334" Version="1.0.334" />
<PackageReference Include="Pkg335" Version="1.0.335" />
<PackageReference Include="Pkg336" Version="1.0.336" />
<PackageReference Include="Pkg337" Version="1.0.337" />
<PackageReference Include="Pkg338" Version="1.0.338" />
<PackageReference Include="Pkg339" Version="1.0.339" />
<PackageReference Include="Pkg340" Version="1.0.340" />
<PackageReference Include="Pkg341" Version="1.0.341" />
<PackageReference Include="Pkg342" Version="1.0.342" />
<PackageReference Include="Pkg343" Version="1.0.343" />
<PackageReference Include="Pkg344" Version="1.0.344" />
<PackageReference Include="Pkg345" Version="1.0.345" />
<PackageReference Include="Pkg346" Version="1.0.346" />
<PackageReference Include="Pkg347" Version="1.0.347" />
<PackageReference Include="Pkg348" Version="1.0.348" />
<PackageReference Include="Pkg349" Version="1.0.349" />
<PackageReference Include="Pkg350" Version="1.0.350" />
<PackageReference Include="Pkg351" Version="1.0.351" />
<PackageReference Include="Pkg352" Version="1.0.352" />
<PackageReference Include="Pkg353" Version="1.0.353" />
<PackageReference Include="Pkg354" Version="1.0.354" />
<PackageReference Include="Pkg355" Version="1.0.355" />
<PackageReference Include="Pkg356" Version="1.0.356" />
<PackageReference Include="Pkg357" Version="1.0.357" />
<PackageReference Include="Pkg358" Version="1.0.358" />
<PackageReference Include="Pkg359" Version="1.0.359" />
<PackageReference Include="Pkg360" Version="1.0.360" />
<PackageReference Include="Pkg361" Version="1.0.361" />
<PackageReference Include="Pkg362" Version="1.0.362" />
<PackageReference Include="Pkg363" Version="1.0.363" />
<PackageReference Include="Pkg364" Version="1.0.364" />
<PackageReference Include="Pkg365" Version="1.0.365" />
<PackageReference Include="Pkg366" Version="1.0.366" />
<PackageReference Include="Pkg367" Version="1.0.367" />
<PackageReference Include="Pkg368" Version="1.0.368" />
<PackageReference Include="Pkg369" Version="1.0.369" />
<PackageReference Include="Pkg370" Version="1.0.370" />
<PackageReference Include="Pkg371" Version="1.0.371" />
<PackageReference Include="Pkg372" Version="1.0.372" />
<PackageReference Include="Pkg373" Version="1.0.373" />
<PackageReference Include="Pkg374" Version="1.0.374" />
<PackageReference Include="Pkg375" Version="1.0.375" />
<PackageReference Include="Pkg376" Version="1.0.376" />
<PackageReference Include="Pkg377" Version="1.0.377" />
<PackageReference Include="Pkg378" Version="1.0.378" />
<PackageReference Include="Pkg379" Version="1.0.379" />
<PackageReference Include="Pkg380" Version="1.0.380" />
<PackageReference Include="Pkg381" Version="1.0.381" />
<PackageReference Include="Pkg382" Version="1.0.382" />
<PackageReference Include="Pkg383" Version="1.0.383" />
<PackageReference Include="Pkg384" Version="1.0.384" />
<PackageReference Include="Pkg385" Version="1.0.385" />
<PackageReference Include="Pkg386" Version="1.0.386" />
<PackageReference Include="Pkg387" Version="1.0.387" />
<PackageReference Include="Pkg388" Version="1.0.388" />
<PackageReference Include="Pkg389" Version="1.0.389" />
<PackageReference Include="Pkg390" Version="1.0.390" />
<PackageReference Include="Pkg391" Version="1.0.391" />
<PackageReference Include="Pkg392" Version="1.0.392" />
<PackageReference Include="Pkg393" Version="1.0.393" />
<PackageReference Include="Pkg394" Version="1.0.394" />
<PackageReference Include="Pkg395" Version="1.0.395" />
<PackageReference Include="Pkg396" Version="1.0.396" />
<PackageReference Include="Pkg397" Version="1.0.397" />
<PackageReference Include="Pkg398" Version="1.0.398" />
<PackageReference Include="Pkg399" Version="1.0.399" />
<PackageReference Include="Pkg400" Version="1.0.400" />
<PackageReference Include="Pkg401" Version="1.0.401" />
<PackageReference Include="Pkg402" Version="1.0.402" />
<PackageReference Include="Pkg403" Version="1.0.403" />
<PackageReference Include="Pkg404" Version="1.0.404" />
<PackageReference Include="Pkg405" Version="1.0.405" />
<PackageReference Include="Pkg406" Version="1.0.406" />
<PackageReference Include="Pkg407" Version="1.0.407" />
<PackageReference Include="Pkg408" Version="1.0.408" />
<PackageReference Include="Pkg409" Version="1.0.409" />
<PackageReference Include="Pkg410" Version="1.0.410" />
<PackageReference Include="Pkg411" Version="1.0.411" />
<PackageReference Include="Pkg412" Version="1.0.412" />
<PackageReference Include="Pkg413" Version="1.0.413" />
<PackageReference Include="Pkg414" Version="1.0.414" />
<PackageReference Include="Pkg415" Version="1.0.415" />
<PackageReference Include="Pkg416" Version="1.0.416" />
<PackageReference Include="Pkg417" Version="1.0.417" />
<PackageReference Include="Pkg418" Version="1.0.418" />
<PackageReference Include="Pkg419" Version="1.0.419" />
<PackageReference Include="Pkg420" Version="1.0.420" />
<PackageReference Include="Pkg421" Version="1.0.421" />
<PackageReference Include="Pkg422" Version="1.0.422" />
<PackageReference Include="Pkg423" Version="1.0.423" />
<PackageReference Include="Pkg424" Version="1.0.424" />
<PackageReference Include="Pkg425" Version="1.0.425" />
<PackageReference Include="Pkg426" Version="1.0.426" />
<PackageReference Include="Pkg427" Version="1.0.427" />
<PackageReference Include="Pkg428" Version="1.0.428" />
<PackageReference Include="Pkg429" Version="1.0.429" />
<PackageReference Include="Pkg430" Version="1.0.430" />
<PackageReference Include="Pkg431" Version="1.0.431" />
<PackageReference Include="Pkg432" Version="1.0.432" />
<PackageReference Include="Pkg433" Version="1.0.433" />
<PackageReference Include="Pkg434" Version="1.0.434" />
<PackageReference Include="Pkg435" Version="1.0.435" />
<PackageReference Include="Pkg436" Version="1.0.436" />
<PackageReference Include="Pkg437" Version="1.0.437" />
<PackageReference Include="Pkg438" Version="1.0.438" />
<PackageReference Include="Pkg439" Version="1.0.439" />
<PackageReference Include="Pkg440" Version="1.0.440" />
<PackageReference Include="Pkg441" Version="1.0.441" />
<PackageReference Include="Pkg442" Version="1.0.442" />
<PackageReference Include="Pkg443" Version="1.0.443" />
<PackageReference Include="Pkg444" Version="1.0.444" />
<PackageReference Include="Pkg445" Version="1.0.445" />
<PackageReference Include="Pkg446" Version="1.0.446" />
<PackageReference Include="Pkg447" Version="1.0.447" />
<PackageReference Include="Pkg448" Version="1.0.448" />
<PackageReference Include="Pkg449" Version="1.0.449" />
<PackageReference Include="Pkg450" Version="1.0.450" />
<PackageReference Include="Pkg451" Version="1.0.451" />
<PackageReference Include="Pkg452" Version="1.0.452" />
<PackageReference Include="Pkg453" Version="1.0.453" />
<PackageReference Include="Pkg454" Version="1.0.454" />
<PackageReference Include="Pkg455" Version="1.0.455" />
<PackageReference Include="Pkg456" Version="1.0.456" />
<PackageReference Include="Pkg457" Version="1.0.457" />
<PackageReference Include="Pkg458" Version="1.0.458" />
<PackageReference Include="Pkg459" Version="1.0.459" />
<PackageReference Include="Pkg460" Version="1.0.460" />
<PackageReference Include="Pkg461" Version="1.0.461" />
<PackageReference Include="Pkg462" Version="1.0.462" />
<PackageReference Include="Pkg463" Version="1.0.463" />
<PackageReference Include="Pkg464" Version="1.0.464" />
<PackageReference Include="Pkg465" Version="1.0.465" />
<PackageReference Include="Pkg466" Version="1.0.466" />
<PackageReference Include="Pkg467" Version="1.0.467" />
<PackageReference Include="Pkg468" Version="1.0.468" />
<PackageReference Include="Pkg469" Version="1.0.469" />
<PackageReference Include="Pkg470" Version="1.0.470" />
<PackageReference Include="Pkg471" Version="1.0.471" />
<PackageReference Include="Pkg472" Version="1.0.472" />
<PackageReference Include="Pkg473" Version="1.0.473" />
<PackageReference Include="Pkg474" Version="1.0.474" />
<PackageReference Include="Pkg475" Version="1.0.475" />
<PackageReference Include="Pkg476" Version="1.0.476" />
<PackageReference Include="Pkg477" Version="1.0.477" />
<PackageReference Include="Pkg478" Version="1.0.478" />
<PackageReference Include="Pkg479" Version="1.0.479" />
<PackageReference Include="Pkg480" Version="1.0.480" />
<PackageReference Include="Pkg481" Version="1.0.481" />
<PackageReference Include="Pkg482" Version="1.0.482" />
<PackageReference Include="Pkg483" Version="1.0.483" />
<PackageReference Include="Pkg484" Version="1.0.484" />
<PackageReference Include="Pkg485" Version="1.0.485" />
<PackageReference Include="Pkg486" Version="1.0.486" />
<PackageReference Include="Pkg487" Version="1.0.487" />
<PackageReference Include="Pkg488" Version="1.0.488" />
<PackageReference Include="Pkg489" Version="1.0.489" />
<PackageReference Include="Pkg490" Version="1.0.490" />
<PackageReference Include="Pkg491" Version="1.0.491" />
<PackageReference Include="Pkg492" Version="1.0.492" />
<PackageReference Include="Pkg493" Version="1.0.493" />
<PackageReference Include="Pkg494" Version="1.0.494" />
<PackageReference Include="Pkg495" Version="1.0.495" />
<PackageReference Include="Pkg496" Version="1.0.496" />
<PackageReference Include="Pkg497" Version="1.0.497" />
<PackageReference Include="Pkg498" Version="1.0.498" />
<PackageReference Include="Pkg499" Version="1.0.499" />
</ItemGroup>
</Project>
