"""Tree-sitter code parsing → knowledge-graph nodes and edges.

Parses source files into structural facts (files, classes, functions/methods,
and their containment + imports) using tree-sitter. Everything extracted here is
``EXTRACTED`` confidence — it comes straight from the AST. Call-graph edges
(which need name resolution and are inherently less certain) come in a later
ticket.

Adding a language = registering its grammar loader, file extensions, and a query
in the tables below; the rest of the pipeline is language-agnostic.
"""

from __future__ import annotations

import logging
import os
from datetime import date
from pathlib import Path

import tree_sitter as ts

from ..logging_setup import log
from .flow.events import extract_event_flow
from .flow.http import extract_http_flow
from .ids import make_id
from .manifest import is_manifest, parse_manifest
from .model import Confidence, Edge, Node, Provenance
from .store.shards import GraphShard

# Directories never worth walking.
_SKIP_DIRS = {".git", "__pycache__", ".venv", "venv", "node_modules", "dist", "build",
              ".mypy_cache", ".pytest_cache", ".ruff_cache", ".tox", ".idea"}

LANG_BY_EXT = {
    ".py": "python",
    ".js": "javascript", ".jsx": "javascript", ".mjs": "javascript", ".cjs": "javascript",
    ".ts": "typescript", ".tsx": "tsx",
    ".cs": "csharp",
}

# A code file larger than this is skipped (and logged). Hand-written source is
# essentially never this big — anything that large is a data blob or vendored
# bundle. Raise [kb] max_file_bytes to index them anyway.
DEFAULT_MAX_FILE_BYTES = 5 * 1024 * 1024

# Generated/derived code (machine-emitted from real sources): graph noise and a
# real time sink in legacy repos. Skipped by default; the source it is generated
# FROM is still indexed, so this is not a knowledge gap. Set [kb] skip_generated
# = false to index it anyway.
_GENERATED_NAME_SUFFIXES = (
    ".designer.cs", ".generated.cs", ".g.cs", ".g.i.cs",
    ".min.js", ".min.mjs", ".min.cjs", ".min.css", ".bundle.js",
)
_GENERATED_BASENAMES = {"assemblyinfo.cs"}
_GENERATED_HEADER_MARKERS = (
    b"<auto-generated", b"@generated", b"do not edit", b"code generated by",
)


def _is_generated_name(filename: str) -> bool:
    low = filename.lower()
    return low.endswith(_GENERATED_NAME_SUFFIXES) or low in _GENERATED_BASENAMES


def _has_generated_header(source: bytes) -> bool:
    """True if a file's first bytes carry a recognised 'this is generated' marker."""
    return any(m in source[:2048].lower() for m in _GENERATED_HEADER_MARKERS)

# tree-sitter node types that introduce a named definition, per language.
_DEF_TYPES = {
    "python": {"class_definition": "class", "function_definition": "function"},
    "javascript": {
        "class_declaration": "class", "function_declaration": "function",
        "method_definition": "method",
    },
    "typescript": {
        "class_declaration": "class", "function_declaration": "function",
        "method_definition": "method", "interface_declaration": "interface",
        "enum_declaration": "enum",
    },
    "csharp": {
        "class_declaration": "class", "interface_declaration": "interface",
        "struct_declaration": "struct", "method_declaration": "method",
    },
}
_DEF_TYPES["tsx"] = _DEF_TYPES["typescript"]

# Queries capture definition *name* identifiers (@def) and import targets (@import).
_QUERIES = {
    "python": """
        (class_definition name: (identifier) @def)
        (function_definition name: (identifier) @def)
        (import_statement (dotted_name) @import)
        (import_from_statement module_name: (dotted_name) @import)
        (call function: (identifier) @call)
        (call function: (attribute attribute: (identifier) @call))
    """,
    "javascript": """
        (class_declaration name: (identifier) @def)
        (function_declaration name: (identifier) @def)
        (method_definition name: (property_identifier) @def)
        (import_statement source: (string) @import)
        (call_expression function: (identifier) @call)
        (call_expression function: (member_expression property: (property_identifier) @call))
    """,
    "typescript": """
        (class_declaration name: (type_identifier) @def)
        (function_declaration name: (identifier) @def)
        (method_definition name: (property_identifier) @def)
        (interface_declaration name: (type_identifier) @def)
        (enum_declaration name: (identifier) @def)
        (import_statement source: (string) @import)
        (call_expression function: (identifier) @call)
        (call_expression function: (member_expression property: (property_identifier) @call))
    """,
    "csharp": """
        (class_declaration name: (identifier) @def)
        (interface_declaration name: (identifier) @def)
        (struct_declaration name: (identifier) @def)
        (method_declaration name: (identifier) @def)
        (using_directive (identifier) @import)
        (using_directive (qualified_name) @import)
        (invocation_expression function: (identifier) @call)
        (invocation_expression function: (member_access_expression name: (identifier) @call))
    """,
}
_QUERIES["tsx"] = _QUERIES["typescript"]

_LANGS: dict[str, ts.Language] = {}
_PARSERS: dict[str, ts.Parser] = {}
_COMPILED: dict[str, ts.Query] = {}


def _language(lang: str) -> ts.Language:
    if lang not in _LANGS:
        if lang == "python":
            import tree_sitter_python as g
            fn = g.language
        elif lang == "javascript":
            import tree_sitter_javascript as g
            fn = g.language
        elif lang == "typescript":
            import tree_sitter_typescript as g
            fn = g.language_typescript
        elif lang == "tsx":
            import tree_sitter_typescript as g
            fn = g.language_tsx
        elif lang == "csharp":
            import tree_sitter_c_sharp as g
            fn = g.language
        else:
            raise ValueError(f"unsupported language: {lang}")
        _LANGS[lang] = ts.Language(fn())
    return _LANGS[lang]


def _parser(lang: str) -> ts.Parser:
    if lang not in _PARSERS:
        _PARSERS[lang] = ts.Parser(_language(lang))
    return _PARSERS[lang]


def _query(lang: str) -> ts.Query:
    if lang not in _COMPILED:
        _COMPILED[lang] = ts.Query(_language(lang), _QUERIES[lang])
    return _COMPILED[lang]


def _enclosing_defs(name_node: ts.Node, def_types: set[str]) -> list[ts.Node]:
    """Definition nodes enclosing this name's definition, innermost first."""
    out = []
    node = name_node.parent.parent if name_node.parent else None
    while node is not None:
        if node.type in def_types:
            out.append(node)
        node = node.parent
    return out


def parse_source(
    repo_id: str, rel_path: str, source: bytes, lang: str, verified_at: date | None = None
) -> tuple[list[Node], list[Edge], list[tuple[str, str, str, int]]]:
    """Parse one file into (nodes, edges, calls).

    ``calls`` are unresolved (caller_id, callee_name, file, line) tuples — call
    targets are resolved repo-wide by :func:`index_repo_dir`.
    """
    verified_at = verified_at or date.today()
    def_types = set(_DEF_TYPES[lang])

    file_id = make_id(repo_id, rel_path)
    file_node = Node(id=file_id, repo=repo_id, kind="file", name=rel_path, file=rel_path, lang=lang)
    nodes: list[Node] = [file_node]
    edges: list[Edge] = []

    tree = _parser(lang).parse(source)
    captures = ts.QueryCursor(_query(lang)).captures(tree.root_node)

    # First pass: a Node for every definition, keyed by its tree-sitter def node id.
    def_node_to_id: dict[int, str] = {}
    pending: list[tuple[ts.Node, str, int]] = []  # (def_ts_node, qualified_name, line)
    for name_node in captures.get("def", []):
        def_ts = name_node.parent
        name = name_node.text.decode("utf-8", "replace")
        enclosing = _enclosing_defs(name_node, def_types)
        scope = [n.child_by_field_name("name").text.decode("utf-8", "replace")
                 for n in reversed(enclosing) if n.child_by_field_name("name")]
        qualified = ".".join([*scope, name])
        line = name_node.start_point[0] + 1
        kind = _DEF_TYPES[lang][def_ts.type]
        if kind == "function" and enclosing and _DEF_TYPES[lang].get(enclosing[0].type) == "class":
            kind = "method"
        nid = make_id(repo_id, rel_path, qualified, str(line))
        def_node_to_id[def_ts.id] = nid
        nodes.append(Node(
            id=nid, repo=repo_id, kind=kind, name=name, qualified_name=f"{rel_path}::{qualified}",
            file=rel_path, line_start=line, line_end=def_ts.end_point[0] + 1, lang=lang,
        ))
        pending.append((def_ts, qualified, line))

    # Second pass: containment edges (parent definition, else the file).
    for def_ts, _qualified, line in pending:
        parent = next((p for p in _enclosing_defs(def_ts.child_by_field_name("name"), def_types)),
                      None)
        parent_id = def_node_to_id.get(parent.id) if parent else file_id
        edges.append(Edge(
            src=parent_id, dst=def_node_to_id[def_ts.id], relation="contains",
            confidence=Confidence.EXTRACTED,
            provenance=Provenance(source_file=rel_path, source_line=line, verified_at=verified_at),
        ))

    # Imports: file -> module node.
    for imp in captures.get("import", []):
        module = imp.text.decode("utf-8", "replace").strip().strip("'\"")
        mid = make_id("module", module)
        nodes.append(Node(id=mid, repo=repo_id, kind="module", name=module, lang=lang))
        edges.append(Edge(
            src=file_id, dst=mid, relation="imports", confidence=Confidence.EXTRACTED,
            provenance=Provenance(source_file=rel_path, source_line=imp.start_point[0] + 1,
                                  verified_at=verified_at),
        ))

    # Calls: (caller_node_id, callee_name, file, line) — resolved repo-wide later.
    calls: list[tuple[str, str, str, int]] = []
    for call_node in captures.get("call", []):
        callee = call_node.text.decode("utf-8", "replace")
        caller_id = file_id
        node = call_node.parent
        while node is not None:
            if node.type in def_types:
                caller_id = def_node_to_id.get(node.id, file_id)
                break
            node = node.parent
        calls.append((caller_id, callee, rel_path, call_node.start_point[0] + 1))

    return nodes, edges, calls


def index_repo_dir(
    repo_path: str, repo_id: str, head_commit: str | None = None,
    languages: list[str] | None = None, *,
    max_file_bytes: int = DEFAULT_MAX_FILE_BYTES, skip_generated: bool = True,
) -> GraphShard:
    """Walk a repository directory and parse every supported file into a shard.

    Generated/derived files (see ``_is_generated_name``/``_has_generated_header``)
    and code files larger than ``max_file_bytes`` are skipped — both reported, never
    silent — to keep legacy monorepos from exploding the graph and the index time.
    """
    root = Path(repo_path)
    allowed_exts = {ext for ext, lang in LANG_BY_EXT.items()
                    if not languages or lang in languages}
    shard = GraphShard(repo=repo_id, head_commit=head_commit)
    by_id: dict[str, Node] = {}
    all_calls: list[tuple[str, str, str, int]] = []
    n_files = n_generated = n_oversize = 0

    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in _SKIP_DIRS]
        for fn in filenames:
            ext = os.path.splitext(fn)[1]
            is_code = ext in allowed_exts
            is_man = is_manifest(fn)
            if not is_code and not is_man:
                continue
            fpath = Path(dirpath) / fn
            rel = str(fpath.relative_to(root))
            # Skip generated/derived code by name, and oversized blobs by stat —
            # both without reading the file.
            if is_code and skip_generated and _is_generated_name(fn):
                n_generated += 1
                continue
            if is_code:
                try:
                    if fpath.stat().st_size > max_file_bytes:
                        n_oversize += 1
                        continue
                except OSError:
                    pass
            try:
                source = fpath.read_bytes()
            except OSError as e:
                log(f"  skip {rel}: {e}")
                continue
            if is_code and skip_generated and _has_generated_header(source):
                n_generated += 1
                continue
            try:
                if is_code:
                    nodes, edges, calls = parse_source(repo_id, rel, source, LANG_BY_EXT[ext])
                    all_calls.extend(calls)
                    # cross-repo flow surfaces: HTTP endpoints + message topics
                    hn, he = extract_http_flow(repo_id, rel, source, LANG_BY_EXT[ext])
                    en, ee = extract_event_flow(repo_id, rel, source, LANG_BY_EXT[ext])
                    nodes += hn + en
                    edges += he + ee
                else:
                    nodes, edges = parse_manifest(repo_id, rel, source)
            except Exception as e:  # noqa: BLE001 - one bad file must not abort the repo
                log(f"  skip {rel}: parse error: {e}")
                continue
            n_files += 1
            for node in nodes:
                by_id[node.id] = node  # dedupe shared nodes (e.g. packages, modules)
            shard.edges.extend(edges)

    shard.nodes.extend(by_id.values())
    shard.edges.extend(_resolve_calls(all_calls, by_id))
    log(f"  parsed {n_files} file(s); skipped {n_generated} generated, "
        f"{n_oversize} oversized", level=logging.DEBUG)
    return shard


def discover_repos(root: str) -> list[tuple[str, str]]:
    """Find git repositories under ``root``: (repo_id, absolute_path) pairs.

    A directory containing a ``.git`` entry is a repo; its ``repo_id`` is its path
    relative to ``root`` (group-relative, matching the local mirror layout), and
    discovery does not descend into a repo once found.
    """
    base = Path(root)
    found = []
    for dirpath, dirnames, _filenames in os.walk(base):
        here = Path(dirpath)
        if (here / ".git").exists():
            rel = here.relative_to(base).as_posix()
            found.append((rel if rel != "." else here.name, str(here)))
            dirnames[:] = []  # don't descend into a repository
            continue
        dirnames[:] = [d for d in dirnames if d not in _SKIP_DIRS]
    return found


# Node kinds that a call can resolve to.
_CALLABLE_KINDS = {"class", "function", "method", "interface", "struct"}


def _resolve_calls(
    calls: list[tuple[str, str, str, int]], nodes_by_id: dict[str, Node]
) -> list[Edge]:
    """Resolve callee names to definitions repo-wide (unambiguous matches only).

    Call edges are INFERRED: resolution is by name, so only names that map to a
    single definition are linked; ambiguous or external callees are skipped.
    """
    name_index: dict[str, set[str]] = {}
    for node in nodes_by_id.values():
        if node.kind in _CALLABLE_KINDS:
            name_index.setdefault(node.name, set()).add(node.id)

    edges, ambiguous = [], 0
    for caller_id, callee, rel, line in calls:
        matches = name_index.get(callee)
        if not matches:
            continue
        if len(matches) > 1:
            ambiguous += 1
            continue
        (target,) = tuple(matches)
        edges.append(Edge(
            src=caller_id, dst=target, relation="calls", confidence=Confidence.INFERRED,
            provenance=Provenance(source_file=rel, source_line=line, verified_at=date.today()),
        ))
    if edges or ambiguous:
        log(f"  resolved {len(edges)} call edge(s) ({ambiguous} ambiguous skipped)",
            level=logging.DEBUG)
    return edges
