"""Tree-sitter code parsing → knowledge-graph nodes and edges.

Parses source files into structural facts (files, classes, functions/methods,
and their containment + imports) using tree-sitter. Everything extracted here is
``EXTRACTED`` confidence — it comes straight from the AST. Call-graph edges
(which need name resolution and are inherently less certain) come in a later
ticket.

Adding a language = registering its grammar loader, file extensions, and a query
in the tables below; the rest of the pipeline is language-agnostic.
"""

from __future__ import annotations

import fnmatch
import logging
import os
import re
from datetime import date
from pathlib import Path

import tree_sitter as ts

from ..logging_setup import log
from .flow.events import extract_event_flow
from .flow.http import extract_http_flow
from .hcl import parse_hcl
from .ids import make_id
from .manifest import is_manifest, parse_manifest
from .model import Confidence, Edge, Node, Provenance
from .store.shards import GraphShard

# Directories never worth walking.
_SKIP_DIRS = {".git", "__pycache__", ".venv", "venv", "node_modules", "dist", "build",
              ".mypy_cache", ".pytest_cache", ".ruff_cache", ".tox", ".idea"}

# Optional per-repo ignore file (gitignore-flavoured *subset*): one glob per line,
# blank lines and `#` comments skipped. Matched with fnmatch against the POSIX path
# relative to the repo root and against the basename, so `*.lock` ignores by name and
# `vendor/` (or `vendor`) ignores a directory and everything under it. No negation /
# `**` / anchoring semantics — a deliberately small, dependency-free subset.
_IGNORE_FILE = ".contextlakeignore"


def load_ignore_patterns(root: Path) -> list[str]:
    f = root / _IGNORE_FILE
    if not f.is_file():
        return []
    try:
        lines = f.read_text(encoding="utf-8", errors="ignore").splitlines()
    except OSError:
        return []
    return [ln.strip() for ln in lines if ln.strip() and not ln.lstrip().startswith("#")]


def match_ignore(rel: str, patterns: list[str]) -> bool:
    """True if the POSIX-relative path ``rel`` is covered by any ignore pattern."""
    rel = rel.replace(os.sep, "/")
    base = rel.rsplit("/", 1)[-1]
    for raw in patterns:
        p = raw.rstrip("/")
        if p and (fnmatch.fnmatch(rel, p) or fnmatch.fnmatch(base, p)
                  or fnmatch.fnmatch(rel, f"{p}/*")):
            return True
    return False

LANG_BY_EXT = {
    ".py": "python",
    ".js": "javascript", ".jsx": "javascript", ".mjs": "javascript", ".cjs": "javascript",
    ".ts": "typescript", ".tsx": "tsx",
    ".cs": "csharp",
    ".go": "go",
    ".java": "java",
    ".c": "c", ".h": "c",
    ".cpp": "cpp", ".cc": "cpp", ".cxx": "cpp", ".c++": "cpp",
    ".hpp": "cpp", ".hh": "cpp", ".hxx": "cpp",
    ".rs": "rust",
    ".rb": "ruby",
    ".php": "php",
    ".scala": "scala", ".sc": "scala",
}

# HCL/Terraform files use a bespoke extraction path (kb/hcl.py), not the OO
# capture model, so they are matched separately from LANG_BY_EXT.
HCL_EXTS = {".tf"}

# A code file larger than this is skipped (and logged). Hand-written source is
# essentially never this big — anything that large is a data blob or vendored
# bundle. Raise [kb] max_file_bytes to index them anyway.
DEFAULT_MAX_FILE_BYTES = 5 * 1024 * 1024

# Generated/derived code (machine-emitted from real sources): graph noise and a
# real time sink in legacy repos. Skipped by default; the source it is generated
# FROM is still indexed, so this is not a knowledge gap. Set [kb] skip_generated
# = false to index it anyway.
_GENERATED_NAME_SUFFIXES = (
    ".designer.cs", ".generated.cs", ".g.cs", ".g.i.cs",
    ".min.js", ".min.mjs", ".min.cjs", ".min.css", ".bundle.js",
)
_GENERATED_BASENAMES = {"assemblyinfo.cs"}
_GENERATED_HEADER_MARKERS = (
    b"<auto-generated", b"@generated", b"do not edit", b"code generated by",
)


def _is_generated_name(filename: str) -> bool:
    low = filename.lower()
    return low.endswith(_GENERATED_NAME_SUFFIXES) or low in _GENERATED_BASENAMES


def _has_generated_header(source: bytes) -> bool:
    """True if a file's first bytes carry a recognised 'this is generated' marker."""
    return any(m in source[:2048].lower() for m in _GENERATED_HEADER_MARKERS)

# tree-sitter node types that introduce a named definition, per language.
_DEF_TYPES = {
    "python": {"class_definition": "class", "function_definition": "function"},
    "javascript": {
        "class_declaration": "class", "function_declaration": "function",
        "method_definition": "method",
    },
    "typescript": {
        "class_declaration": "class", "function_declaration": "function",
        "method_definition": "method", "interface_declaration": "interface",
        "enum_declaration": "enum",
    },
    "csharp": {
        "class_declaration": "class", "interface_declaration": "interface",
        "struct_declaration": "struct", "method_declaration": "method",
    },
    # Go has no classes; a `type_spec` names a struct/interface/alias — all indexed
    # as a "struct"-kind type node (the field that distinguishes them is not the node
    # type the kind is keyed on). Methods are top-level with a receiver.
    "go": {
        "function_declaration": "function", "method_declaration": "method",
        "type_spec": "struct",
    },
    "java": {
        "class_declaration": "class", "interface_declaration": "interface",
        "enum_declaration": "enum", "record_declaration": "class",
        "method_declaration": "method", "constructor_declaration": "method",
    },
    # C/C++: a function's name sits under a *_declarator, so parse_source normalizes
    # the def node up to the enclosing function_definition (see _def_node) — that is
    # the type keyed here, so call attribution and containment resolve correctly.
    "c": {
        "function_definition": "function", "struct_specifier": "struct",
        "enum_specifier": "enum", "union_specifier": "struct",
    },
    "cpp": {
        "function_definition": "function", "class_specifier": "class",
        "struct_specifier": "struct", "enum_specifier": "enum",
        "union_specifier": "struct",
    },
    "rust": {
        "function_item": "function", "struct_item": "struct",
        "enum_item": "enum", "trait_item": "interface",
    },
    "ruby": {   # Ruby has no free functions — every `def` is a method
        "class": "class", "module": "class",
        "method": "method", "singleton_method": "method",
    },
    "php": {
        "class_declaration": "class", "interface_declaration": "interface",
        "trait_declaration": "class", "enum_declaration": "enum",
        "function_definition": "function", "method_declaration": "method",
    },
    "scala": {
        "class_definition": "class", "object_definition": "class",
        "trait_definition": "interface", "function_definition": "function",
    },
}
_DEF_TYPES["tsx"] = _DEF_TYPES["typescript"]

# Queries capture definition *name* identifiers (@def) and import targets (@import).
_QUERIES = {
    "python": """
        (class_definition name: (identifier) @def)
        (function_definition name: (identifier) @def)
        (import_statement (dotted_name) @import)
        (import_from_statement module_name: (dotted_name) @import)
        (call function: (identifier) @call)
        (call function: (attribute attribute: (identifier) @call))
        (class_definition superclasses: (argument_list [(identifier) (attribute)] @base))
    """,
    "javascript": """
        (class_declaration name: (identifier) @def)
        (function_declaration name: (identifier) @def)
        (method_definition name: (property_identifier) @def)
        (import_statement source: (string) @import)
        (call_expression function: (identifier) @call)
        (call_expression function: (member_expression property: (property_identifier) @call))
        (class_heritage (identifier) @base)
    """,
    "typescript": """
        (class_declaration name: (type_identifier) @def)
        (function_declaration name: (identifier) @def)
        (method_definition name: (property_identifier) @def)
        (interface_declaration name: (type_identifier) @def)
        (enum_declaration name: (identifier) @def)
        (import_statement source: (string) @import)
        (call_expression function: (identifier) @call)
        (call_expression function: (member_expression property: (property_identifier) @call))
        (extends_clause [(identifier) (type_identifier)] @base)
        (implements_clause [(type_identifier) (identifier)] @base)
        (extends_type_clause [(type_identifier) (identifier)] @base)
    """,
    "csharp": """
        (class_declaration name: (identifier) @def)
        (interface_declaration name: (identifier) @def)
        (struct_declaration name: (identifier) @def)
        (method_declaration name: (identifier) @def)
        (using_directive (identifier) @import)
        (using_directive (qualified_name) @import)
        (invocation_expression function: (identifier) @call)
        (invocation_expression function: (member_access_expression name: (identifier) @call))
        (base_list [(identifier) (generic_name)] @base)
    """,
    "go": """
        (function_declaration name: (identifier) @def)
        (method_declaration name: (field_identifier) @def)
        (type_spec name: (type_identifier) @def)
        (import_spec path: (interpreted_string_literal) @import)
        (call_expression function: (identifier) @call)
        (call_expression function: (selector_expression field: (field_identifier) @call))
    """,
    "java": """
        (class_declaration name: (identifier) @def)
        (interface_declaration name: (identifier) @def)
        (enum_declaration name: (identifier) @def)
        (record_declaration name: (identifier) @def)
        (method_declaration name: (identifier) @def)
        (constructor_declaration name: (identifier) @def)
        (import_declaration (scoped_identifier) @import)
        (method_invocation name: (identifier) @call)
        (superclass (type_identifier) @base)
        (super_interfaces (type_list (type_identifier) @base))
        (extends_interfaces (type_list (type_identifier) @base))
    """,
    "c": """
        (function_definition declarator: (function_declarator declarator: (identifier) @def))
        (function_definition declarator: (pointer_declarator declarator:
            (function_declarator declarator: (identifier) @def)))
        (struct_specifier name: (type_identifier) @def)
        (enum_specifier name: (type_identifier) @def)
        (union_specifier name: (type_identifier) @def)
        (preproc_include path: (string_literal) @import)
        (preproc_include path: (system_lib_string) @import)
        (call_expression function: (identifier) @call)
    """,
    "cpp": """
        (class_specifier name: (type_identifier) @def)
        (struct_specifier name: (type_identifier) @def)
        (enum_specifier name: (type_identifier) @def)
        (function_definition declarator: (function_declarator declarator: (identifier) @def))
        (function_definition declarator: (function_declarator declarator: (field_identifier) @def))
        (function_definition declarator: (function_declarator declarator:
            (qualified_identifier name: (identifier) @def)))
        (preproc_include path: (string_literal) @import)
        (preproc_include path: (system_lib_string) @import)
        (call_expression function: (identifier) @call)
        (call_expression function: (field_expression field: (field_identifier) @call))
        (base_class_clause (type_identifier) @base)
    """,
    "rust": """
        (function_item name: (identifier) @def)
        (struct_item name: (type_identifier) @def)
        (enum_item name: (type_identifier) @def)
        (trait_item name: (type_identifier) @def)
        (use_declaration argument: (scoped_identifier) @import)
        (use_declaration argument: (identifier) @import)
        (call_expression function: (identifier) @call)
        (call_expression function: (field_expression field: (field_identifier) @call))
        (call_expression function: (scoped_identifier name: (identifier) @call))
    """,
    "ruby": """
        (class name: (constant) @def)
        (module name: (constant) @def)
        (method name: (identifier) @def)
        (singleton_method name: (identifier) @def)
        (call method: (identifier) @call)
        (superclass (constant) @base)
    """,
    "php": """
        (class_declaration name: (name) @def)
        (interface_declaration name: (name) @def)
        (trait_declaration name: (name) @def)
        (enum_declaration name: (name) @def)
        (function_definition name: (name) @def)
        (method_declaration name: (name) @def)
        (namespace_use_clause (qualified_name) @import)
        (function_call_expression function: (name) @call)
        (member_call_expression name: (name) @call)
        (scoped_call_expression name: (name) @call)
        (base_clause (name) @base)
        (class_interface_clause (name) @base)
    """,
    "scala": """
        (class_definition name: (identifier) @def)
        (object_definition name: (identifier) @def)
        (trait_definition name: (identifier) @def)
        (function_definition name: (identifier) @def)
        (call_expression (identifier) @call)
        (extends_clause (type_identifier) @base)
    """,
}
_QUERIES["tsx"] = _QUERIES["typescript"]

_LANGS: dict[str, ts.Language] = {}
_PARSERS: dict[str, ts.Parser] = {}
_COMPILED: dict[str, ts.Query] = {}


def _language(lang: str) -> ts.Language:
    if lang not in _LANGS:
        if lang == "python":
            import tree_sitter_python as g
            fn = g.language
        elif lang == "javascript":
            import tree_sitter_javascript as g
            fn = g.language
        elif lang == "typescript":
            import tree_sitter_typescript as g
            fn = g.language_typescript
        elif lang == "tsx":
            import tree_sitter_typescript as g
            fn = g.language_tsx
        elif lang == "csharp":
            import tree_sitter_c_sharp as g
            fn = g.language
        elif lang == "go":
            import tree_sitter_go as g
            fn = g.language
        elif lang == "java":
            import tree_sitter_java as g
            fn = g.language
        elif lang == "c":
            import tree_sitter_c as g
            fn = g.language
        elif lang == "cpp":
            import tree_sitter_cpp as g
            fn = g.language
        elif lang == "rust":
            import tree_sitter_rust as g
            fn = g.language
        elif lang == "ruby":
            import tree_sitter_ruby as g
            fn = g.language
        elif lang == "php":
            import tree_sitter_php as g
            fn = g.language_php
        elif lang == "scala":
            import tree_sitter_scala as g
            fn = g.language
        else:
            raise ValueError(f"unsupported language: {lang}")
        _LANGS[lang] = ts.Language(fn())
    return _LANGS[lang]


def _parser(lang: str) -> ts.Parser:
    if lang not in _PARSERS:
        _PARSERS[lang] = ts.Parser(_language(lang))
    return _PARSERS[lang]


def _query(lang: str) -> ts.Query:
    if lang not in _COMPILED:
        _COMPILED[lang] = ts.Query(_language(lang), _QUERIES[lang])
    return _COMPILED[lang]


def _leading_doc(def_ts: ts.Node) -> str | None:
    """A definition's leading doc-comment — JSDoc ``/** */`` or C# ``///`` XML docs.

    Restricted to *doc-comment* syntax (not plain ``//`` / ``/*``) so a stray code
    comment above a function isn't mistaken for documentation. Collects the contiguous
    run of doc-comments immediately above the def, strips the comment + XML syntax.
    """
    raws: list[str] = []
    node = def_ts.prev_sibling
    last_line = def_ts.start_point[0]
    while node is not None and node.type == "comment" and last_line - node.end_point[0] <= 1:
        raw = node.text.decode("utf-8", "replace").strip()
        if not (raw.startswith("/**") or raw.startswith("///")):
            break  # a plain comment ends the doc run
        raws.append(raw)
        last_line = node.start_point[0]
        node = node.prev_sibling
    if not raws:
        return None
    parts: list[str] = []
    for raw in reversed(raws):
        if raw.startswith("/**"):
            inner = raw[3:-2] if raw.endswith("*/") else raw[3:]
            parts += [ln.strip().lstrip("*").strip() for ln in inner.splitlines()]
        else:  # /// XML doc line
            parts.append(raw.lstrip("/").strip())
    doc = re.sub(r"<[^>]+>", " ", " ".join(p for p in parts if p))
    doc = " ".join(doc.split())  # collapse whitespace left by tag/comment stripping
    return doc[:1000] or None


def _doc_sig(def_ts: ts.Node, lang: str) -> dict:
    """Capture a definition's signature (parameters) and docstring as node attrs.

    Additive, best-effort — richer graph facts (shown in the UI, wiki, and
    ``get_repo_brief``) and the groundwork for body-aware embeddings. Signature is
    captured across languages (py/js/ts/c#); the docstring comes from Python's
    first-statement string or, elsewhere, a JSDoc/C#-XML leading comment. Never raises.
    """
    out: dict = {}
    try:
        # signature: the parameter list — generalizes across languages (field name
        # is "parameters" in py/js/ts, "parameter_list" in c#); graceful if absent.
        params = (def_ts.child_by_field_name("parameters")
                  or def_ts.child_by_field_name("parameter_list"))
        if params is not None:
            sig = params.text.decode("utf-8", "replace").strip()
            if sig:
                out["signature"] = sig[:300]
        if lang == "python":
            body = def_ts.child_by_field_name("body")
            if body is not None and body.named_child_count:
                first = body.named_child(0)
                if first.type == "expression_statement" and first.named_child_count:
                    lit = first.named_child(0)
                    if lit.type == "string":
                        doc = lit.text.decode("utf-8", "replace").lstrip("rRbBuUfF")
                        doc = doc.strip().strip("\"'").strip()
                        if doc:
                            out["doc"] = doc[:1000]
        else:
            doc = _leading_doc(def_ts)
            if doc:
                out["doc"] = doc
    except Exception:  # noqa: BLE001 - capture is best-effort, never blocks indexing
        return out
    return out


def _def_node(name_node: ts.Node, def_types: set[str]) -> ts.Node | None:
    """The definition node a captured ``@def`` name belongs to.

    Usually ``name_node.parent`` (the name is a direct child of the def node). In
    C/C++ the name sits under one or more ``*_declarator`` wrappers, so climb to the
    enclosing def-typed node (the ``function_definition``) — that is what encloses the
    body, so call attribution and containment resolve to it.
    """
    node = name_node.parent
    while node is not None and node.type not in def_types:
        node = node.parent
    return node


def _enclosing_defs(name_node: ts.Node, def_types: set[str]) -> list[ts.Node]:
    """Definition nodes enclosing this name's definition, innermost first (the name's
    own definition node is excluded)."""
    own = _def_node(name_node, def_types)
    out = []
    node = own.parent if own is not None else (
        name_node.parent.parent if name_node.parent else None)
    while node is not None:
        if node.type in def_types:
            out.append(node)
        node = node.parent
    return out


def parse_source(
    repo_id: str, rel_path: str, source: bytes, lang: str, verified_at: date | None = None
) -> tuple[list[Node], list[Edge], list[tuple[str, str, str, int]],
           list[tuple[str, str, str, int]]]:
    """Parse one file into (nodes, edges, calls, inherits).

    ``calls`` and ``inherits`` are unresolved (src_id, target_name, file, line)
    tuples — the target definition (a callee, or a base class/interface) is
    resolved repo-wide by :func:`index_repo_dir`, since it may live in another file.
    """
    verified_at = verified_at or date.today()
    def_types = set(_DEF_TYPES[lang])

    file_id = make_id(repo_id, rel_path)
    file_node = Node(id=file_id, repo=repo_id, kind="file", name=rel_path, file=rel_path, lang=lang)
    nodes: list[Node] = [file_node]
    edges: list[Edge] = []

    tree = _parser(lang).parse(source)
    captures = ts.QueryCursor(_query(lang)).captures(tree.root_node)

    # First pass: a Node for every definition, keyed by its tree-sitter def node id.
    def_node_to_id: dict[int, str] = {}
    pending: list[tuple[ts.Node, str, int]] = []  # (def_ts_node, qualified_name, line)
    for name_node in captures.get("def", []):
        def_ts = _def_node(name_node, def_types)
        if def_ts is None:
            continue   # a declarator with no enclosing def node (defensive)
        name = name_node.text.decode("utf-8", "replace")
        enclosing = _enclosing_defs(name_node, def_types)
        scope = [n.child_by_field_name("name").text.decode("utf-8", "replace")
                 for n in reversed(enclosing) if n.child_by_field_name("name")]
        qualified = ".".join([*scope, name])
        line = name_node.start_point[0] + 1
        kind = _DEF_TYPES[lang][def_ts.type]
        if kind == "function" and enclosing and _DEF_TYPES[lang].get(enclosing[0].type) == "class":
            kind = "method"
        nid = make_id(repo_id, rel_path, qualified, str(line))
        def_node_to_id[def_ts.id] = nid
        nodes.append(Node(
            id=nid, repo=repo_id, kind=kind, name=name, qualified_name=f"{rel_path}::{qualified}",
            file=rel_path, line_start=line, line_end=def_ts.end_point[0] + 1, lang=lang,
            attrs=_doc_sig(def_ts, lang),
        ))
        pending.append((def_ts, qualified, line))

    # Second pass: containment edges (parent definition, else the file). The parent is
    # the nearest enclosing def-typed node above this one — computed from def_ts itself
    # (a C/C++ function_definition has no "name" field to walk from).
    for def_ts, _qualified, line in pending:
        parent = def_ts.parent
        while parent is not None and parent.type not in def_types:
            parent = parent.parent
        parent_id = def_node_to_id.get(parent.id) if parent else file_id
        edges.append(Edge(
            src=parent_id, dst=def_node_to_id[def_ts.id], relation="contains",
            confidence=Confidence.EXTRACTED,
            provenance=Provenance(source_file=rel_path, source_line=line, verified_at=verified_at),
        ))

    # Imports: file -> module node.
    for imp in captures.get("import", []):
        module = imp.text.decode("utf-8", "replace").strip().strip("'\"")
        mid = make_id("module", module)
        nodes.append(Node(id=mid, repo=repo_id, kind="module", name=module, lang=lang))
        edges.append(Edge(
            src=file_id, dst=mid, relation="imports", confidence=Confidence.EXTRACTED,
            provenance=Provenance(source_file=rel_path, source_line=imp.start_point[0] + 1,
                                  verified_at=verified_at),
        ))

    # Calls: (caller_node_id, callee_name, file, line) — resolved repo-wide later.
    calls: list[tuple[str, str, str, int]] = []
    for call_node in captures.get("call", []):
        callee = call_node.text.decode("utf-8", "replace")
        caller_id = file_id
        node = call_node.parent
        while node is not None:
            if node.type in def_types:
                caller_id = def_node_to_id.get(node.id, file_id)
                break
            node = node.parent
        calls.append((caller_id, callee, rel_path, call_node.start_point[0] + 1))

    # Inherits: (subclass_id, base_name, file, line) — the base may be defined in
    # another file, so resolve repo-wide later (like calls). A dotted/qualified base
    # (django.views.View) keeps only its last segment, matching how defs are named.
    inherits: list[tuple[str, str, str, int]] = []
    for base_node in captures.get("base", []):
        base = base_node.text.decode("utf-8", "replace").split(".")[-1].strip()
        sub_id = None
        node = base_node.parent
        while node is not None:
            if node.type in def_types and node.id in def_node_to_id:
                sub_id = def_node_to_id[node.id]
                break
            node = node.parent
        if sub_id and base:
            inherits.append((sub_id, base, rel_path, base_node.start_point[0] + 1))

    return nodes, edges, calls, inherits


def index_repo_dir(
    repo_path: str, repo_id: str, head_commit: str | None = None,
    languages: list[str] | None = None, *,
    max_file_bytes: int = DEFAULT_MAX_FILE_BYTES, skip_generated: bool = True,
) -> GraphShard:
    """Walk a repository directory and parse every supported file into a shard.

    Generated/derived files (see ``_is_generated_name``/``_has_generated_header``)
    and code files larger than ``max_file_bytes`` are skipped — both reported, never
    silent — to keep legacy monorepos from exploding the graph and the index time.
    """
    root = Path(repo_path)
    allowed_exts = {ext for ext, lang in LANG_BY_EXT.items()
                    if not languages or lang in languages}
    index_hcl = not languages or "hcl" in languages
    ignore = load_ignore_patterns(root)
    shard = GraphShard(repo=repo_id, head_commit=head_commit)
    by_id: dict[str, Node] = {}
    all_calls: list[tuple[str, str, str, int]] = []
    all_inherits: list[tuple[str, str, str, int]] = []
    all_hcl_refs: list[tuple[str, str, str, int]] = []
    n_files = n_generated = n_oversize = n_ignored = 0

    for dirpath, dirnames, filenames in os.walk(root):
        relbase = os.path.relpath(dirpath, root)
        relbase = "" if relbase == "." else relbase.replace(os.sep, "/")
        dirnames[:] = [d for d in dirnames if d not in _SKIP_DIRS
                       and not (ignore and match_ignore(f"{relbase}/{d}".lstrip("/"), ignore))]
        for fn in filenames:
            ext = os.path.splitext(fn)[1]
            is_code = ext in allowed_exts
            is_hcl = index_hcl and ext in HCL_EXTS
            is_man = is_manifest(fn)
            if not is_code and not is_hcl and not is_man:
                continue
            fpath = Path(dirpath) / fn
            rel = str(fpath.relative_to(root))
            if ignore and match_ignore(rel, ignore):
                n_ignored += 1
                continue
            # Skip generated/derived code by name, and oversized blobs by stat —
            # both without reading the file.
            if is_code and skip_generated and _is_generated_name(fn):
                n_generated += 1
                continue
            if is_code or is_hcl:
                try:
                    if fpath.stat().st_size > max_file_bytes:
                        n_oversize += 1
                        continue
                except OSError:
                    pass
            try:
                source = fpath.read_bytes()
            except OSError as e:
                log(f"  skip {rel}: {e}")
                continue
            if is_code and skip_generated and _has_generated_header(source):
                n_generated += 1
                continue
            try:
                if is_hcl:
                    nodes, hcl_refs = parse_hcl(repo_id, rel, source)
                    edges = []
                    all_hcl_refs.extend(hcl_refs)
                elif is_code:
                    nodes, edges, calls, inh = parse_source(repo_id, rel, source,
                                                            LANG_BY_EXT[ext])
                    all_calls.extend(calls)
                    all_inherits.extend(inh)
                    # cross-repo flow surfaces: HTTP endpoints + message topics
                    hn, he = extract_http_flow(repo_id, rel, source, LANG_BY_EXT[ext])
                    en, ee = extract_event_flow(repo_id, rel, source, LANG_BY_EXT[ext])
                    nodes += hn + en
                    edges += he + ee
                else:
                    nodes, edges = parse_manifest(repo_id, rel, source)
            except Exception as e:  # noqa: BLE001 - one bad file must not abort the repo
                log(f"  skip {rel}: parse error: {e}")
                continue
            n_files += 1
            for node in nodes:
                by_id[node.id] = node  # dedupe shared nodes (e.g. packages, modules)
            shard.edges.extend(edges)

    shard.nodes.extend(by_id.values())
    shard.edges.extend(_resolve_name_refs(
        all_calls, by_id, relation="calls", target_kinds=_CALLABLE_KINDS))
    shard.edges.extend(_resolve_name_refs(
        all_inherits, by_id, relation="inherits", target_kinds=_INHERITABLE_KINDS))
    shard.edges.extend(_resolve_name_refs(
        all_hcl_refs, by_id, relation="depends_on", target_kinds=_HCL_KINDS))
    log(f"  parsed {n_files} file(s); skipped {n_generated} generated, "
        f"{n_oversize} oversized, {n_ignored} ignored", level=logging.DEBUG)
    return shard


def discover_repos(root: str) -> list[tuple[str, str]]:
    """Find git repositories under ``root``: (repo_id, absolute_path) pairs.

    A directory containing a ``.git`` entry is a repo; its ``repo_id`` is its path
    relative to ``root`` (group-relative, matching the local mirror layout), and
    discovery does not descend into a repo once found.
    """
    base = Path(root)
    found = []
    for dirpath, dirnames, _filenames in os.walk(base):
        here = Path(dirpath)
        if (here / ".git").exists():
            rel = here.relative_to(base).as_posix()
            found.append((rel if rel != "." else here.name, str(here)))
            dirnames[:] = []  # don't descend into a repository
            continue
        dirnames[:] = [d for d in dirnames if d not in _SKIP_DIRS]
    return found


# Node kinds a call can resolve to, and the (narrower) kinds a base class/interface
# can resolve to. A method can be called but never inherited from.
_CALLABLE_KINDS = {"class", "function", "method", "interface", "struct"}
_INHERITABLE_KINDS = {"class", "interface", "struct"}

# HCL block kinds a depends_on reference can resolve to (disjoint from code
# symbol kinds, so their name index never collides with calls/inherits).
_HCL_KINDS = {"resource", "data", "variable", "output", "module", "local"}


# A name that resolves to 2..N definitions is emitted as AMBIGUOUS edges to each
# candidate (so blast-radius doesn't miss hot symbols); a name matching more than
# this is too generic (e.g. `get`/`handle`) to be signal and is skipped.
_MAX_AMBIG_FANOUT = 6


def _resolve_name_refs(
    refs: list[tuple[str, str, str, int]], nodes_by_id: dict[str, Node],
    *, relation: str, target_kinds: set[str],
) -> list[Edge]:
    """Resolve ``(src_id, target_name, file, line)`` references to definitions
    repo-wide, emitting ``relation`` edges. Shared by calls and inherits.

    An edge is INFERRED when a name maps to a single definition. A name mapping to
    2..``_MAX_AMBIG_FANOUT`` definitions is genuinely ambiguous — rather than drop it
    (which silently loses the hottest symbols and undercounts blast radius), emit an
    AMBIGUOUS edge to each candidate. Names matching more than the cap are too generic
    to be signal and are skipped; self-references and duplicate (src, dst) pairs are
    de-duplicated.
    """
    name_index: dict[str, set[str]] = {}
    for node in nodes_by_id.values():
        if node.kind in target_kinds:
            name_index.setdefault(node.name, set()).add(node.id)

    edges: list[Edge] = []
    seen: set[tuple[str, str]] = set()
    resolved = ambiguous = dropped = 0
    for src_id, name, rel, line in refs:
        matches = name_index.get(name)
        if not matches:
            continue
        if len(matches) == 1:
            conf, targets = Confidence.INFERRED, list(matches)
        elif len(matches) <= _MAX_AMBIG_FANOUT:
            conf, targets = Confidence.AMBIGUOUS, sorted(matches)  # deterministic
            ambiguous += 1
        else:
            dropped += 1  # too many candidates -> noise
            continue
        for target in targets:
            if target == src_id or (src_id, target) in seen:
                continue
            seen.add((src_id, target))
            edges.append(Edge(
                src=src_id, dst=target, relation=relation, confidence=conf,
                context="ambiguous" if conf is Confidence.AMBIGUOUS else None,
                provenance=Provenance(source_file=rel, source_line=line,
                                      verified_at=date.today())))
            if conf is Confidence.INFERRED:
                resolved += 1
    if edges or dropped:
        log(f"  resolved {resolved} {relation} edge(s); {ambiguous} ambiguous "
            f"(<= {_MAX_AMBIG_FANOUT} candidates), {dropped} too-generic skipped",
            level=logging.DEBUG)
    return edges
