"""Render workspace-specific steering files from the knowledge graph.

All renderers are pure: ``(facts, ...) -> str``. ``workspace_facts`` gathers the
specifics (repos, languages, shared dependencies) from the store + shards; the
guardrails are generic and tool-agnostic.
"""

from __future__ import annotations

from collections import Counter

from ..store.shards import read_shard

# Managed-block markers. Steering markdown is wrapped between BEGIN/END so an
# existing user file is *enhanced* (our block appended/refreshed) rather than
# overwritten — content outside the block is never touched.
BEGIN = "<!-- BEGIN contextlake (managed; this block is refreshed by `contextlake steer`) -->"
END = "<!-- END contextlake -->"
MARKER = BEGIN  # presence marks contextlake-managed content

GUARDRAILS = """\
## Guardrails (non-negotiable)

- **Cite, don't guess.** Every claim about a repo, API, file, or behavior must trace
  to a file you actually read this session — use the knowledge tools below to find
  and open it. No source means say so and go read it; do not invent.
- **Protect work in progress.** Never switch branches, reset, or discard uncommitted
  changes. Assume every checked-out branch is someone's live work.
- **Surgical changes.** Match the surrounding style; touch only what the task needs;
  no speculative refactors or drive-by rewrites.
- **Stop and ask** before destructive or irreversible actions, architecture
  decisions, scope expansion, or anything touching secrets, IAM, or production.
"""


def workspace_facts(store, store_dir) -> dict:
    """Gather workspace specifics from the store and per-repo shards."""
    repos = store.list_repos()
    langs: Counter = Counter()
    packages: Counter = Counter()
    per_repo = []
    for r in repos:
        shard = read_shard(store_dir, r.id)
        if shard is None:
            per_repo.append({"id": r.id, "nodes": 0, "langs": []})
            continue
        rlangs: Counter = Counter()
        for n in shard.nodes:
            if n.lang:
                langs[n.lang] += 1
                rlangs[n.lang] += 1
            if n.kind == "package":
                packages[n.name] += 1
        per_repo.append({"id": r.id, "nodes": len(shard.nodes),
                         "langs": [lang for lang, _ in rlangs.most_common(3)]})
    st = store.stats()
    return {
        "count": len(repos),
        "languages": [lang for lang, _ in langs.most_common()],
        "top_packages": [p for p, _ in packages.most_common(15)],
        "nodes": st.nodes,
        "edges": st.edges,
        "per_repo": sorted(per_repo, key=lambda d: d["nodes"], reverse=True),
        # Which store these numbers came from. `--out` picks where the file is
        # written but the config chain picks the store, so the two can disagree
        # silently: running steer from a different directory rewrote a correct
        # 5,500-symbol AGENTS.md down to a two-symbol one, exit 0, no warning,
        # and every number in it was right for the store that happened to
        # resolve. Naming the store makes that swap visible in the diff.
        "store": str(store_dir),
    }


def _serve_cmd(config_path: str | None) -> str:
    return "contextlake kb serve" + (f" --config {config_path}" if config_path else "")


def _repos(n: int) -> str:
    return f"{n} repository" if n == 1 else f"{n} repositories"


def _md_safe(s: str) -> str:
    """Neutralize text (a repo id, package name, ...) headed into the managed
    markdown block: strip backticks so it can't break out of a code span, and
    strip the literal BEGIN/END splice markers so a hostile value (e.g. an
    npm/pypi dependency name pulled in verbatim by manifest.py) can never
    reintroduce a marker mid-body and corrupt the next `contextlake steer` refresh.
    """
    s = (s or "").replace("`", "'")
    for marker in (BEGIN, END):
        s = s.replace(marker, "")
    return s


def _repo_lines(facts: dict, limit: int = 40) -> str:
    rows = facts["per_repo"][:limit]
    out = "\n".join(
        f"- `{_md_safe(r['id'])}` — {r['nodes']} symbols"
        + (f" ({', '.join(_md_safe(lang) for lang in r['langs'])})" if r["langs"] else "")
        for r in rows
    )
    if len(facts["per_repo"]) > limit:
        out += f"\n- … and {len(facts['per_repo']) - limit} more"
    return out or "- (none indexed yet — run `contextlake kb index --workspace .`)"


def render_agents_md(facts: dict, *, config_path: str | None = None) -> str:
    langs = ", ".join(facts["languages"]) or "—"
    pkgs = ", ".join(f"`{_md_safe(p)}`" for p in facts["top_packages"][:10]) or "—"
    return f"""# AGENTS.md — Workspace guide for AI coding agents

This directory mirrors **{_repos(facts['count'])}** in their original namespace
structure, each parked on its most active branch. A local knowledge graph
({facts['nodes']} symbols, {facts['edges']} relations) indexes them.

Generated by `contextlake kb steer` from the knowledge store at
`{_md_safe(facts.get('store') or 'unknown')}`. If those counts look wrong, check that
this is the store you meant -- the output path and the store are chosen
separately.

- **Languages:** {langs}
- **Most-shared dependencies:** {pkgs}

## Get context before grepping

A knowledge server exposes the graph over MCP — prefer it over brute-force search:

```
{_serve_cmd(config_path)}
```

Tools it provides: `search_code` (find symbols), `find_definition`, `find_callers`
and `find_callees` (both cite the line the call is written on),
`find_dependents`, `shortest_path`, `graph_stats`, and — when embeddings are enabled
— `semantic_search` / `hybrid_search` for natural-language queries. Curated wiki
pages (if generated) live under the knowledge store's `wiki/`.

## Repositories

{_repo_lines(facts)}

{GUARDRAILS}"""


def render_claude_md(config_path: str | None = None) -> str:
    return f"""# CLAUDE.md

See @AGENTS.md for the workspace overview, the knowledge tools, and the guardrails —
they apply here verbatim.

The knowledge-graph MCP server is configured for this workspace in `.mcp.json`
(it runs `{_serve_cmd(config_path)}`). Query it before searching by hand.
"""


def render_windsurfrules(facts: dict, *, config_path: str | None = None) -> str:
    return f"""# Workspace rules (Windsurf)

This workspace mirrors {_repos(facts['count'])} with a local knowledge graph.
Reach it over MCP (`{_serve_cmd(config_path)}`, also in this workspace's MCP config)
and query it before grepping. See AGENTS.md for the full guide.

{GUARDRAILS}"""


def render_kiro_steering(facts: dict, *, config_path: str | None = None) -> str:
    return f"""# Workspace steering (Kiro)

{_repos(facts['count'])}, mirrored and indexed into a local knowledge graph reachable
over MCP (`{_serve_cmd(config_path)}`). Prefer graph queries over manual search; see
AGENTS.md for tools and repo list.

{GUARDRAILS}"""


def mcp_server_entry(config_path: str | None = None) -> dict:
    """The MCP server entry for this workspace.

    The per-server shape (``command``/``args``) is identical across clients;
    only the top-level wrapper key differs (``.mcp.json`` -> ``mcpServers``,
    VS Code's ``.vscode/mcp.json`` -> ``servers``), so this one dict is reused
    for both.
    """
    args = ["kb", "serve"]
    if config_path:
        args += ["--config", config_path]
    return {"command": "contextlake", "args": args}


SESSION_HOOK_MARK = "kb refresh --hook"
"""How an installed session hook is recognised as ours.

There is no marker comment in JSON and no END delimiter, so identity has to live in
the command string itself. ``kb steer`` matches on this to *replace* its own entry
instead of appending a second copy every time it runs -- the same idempotence the
markdown files get from their BEGIN/END block."""


def session_hook_entry(config_path: str | None = None) -> dict:
    """The SessionStart hook entry: report graph freshness, refresh in the background.

    Shape verified against the hook definitions Claude Code's own plugins ship
    (``{"type": "command", "command": ..., "timeout": ...}`` inside a matcher group).
    **Claude Code only** -- other editors' session-lifecycle schemas are not something
    this has been checked against, so nothing here claims them.

    The timeout guards the bounded freshness check, not the update: the update is
    detached, so the hook returns as soon as it has something to say.
    """
    from shlex import quote

    cmd = "contextlake kb refresh --hook --refresh"
    if config_path:
        # Quoted: this string is handed to a shell, and a store path with a space in it
        # would otherwise install a hook that silently reads the wrong config.
        cmd += f" --config {quote(config_path)}"
    return {"type": "command", "command": cmd, "timeout": 20}
